import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { DeviceStoreProvider } from "@/providers/device-store-provider";
import { ViewportStoreProvider } from "@/providers/viewport-store-provider";
import Layout from "@/components/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <DeviceStoreProvider>
        <ViewportStoreProvider>
          <body className={inter.className}>
            <Layout>{children}</Layout>
          </body>
        </ViewportStoreProvider>
      </DeviceStoreProvider>
    </html>
  );
}
